### ISSUE TITLE
Windows Install Issue

### ISSUE THREAD

**Issue by OpenDataAlex** [OpenDataAlex/etlTest#28]
From a user who tried to install etlTest on Windows 7:

```
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\<user>\appdata\local\temp\pip_build_<user>\etlTest\setup.py",
 line 101, in <module>

    'etltest/templates/settings/tools.yml'

  File "C:\Python27\lib\distutils\core.py", line 151, in setup

    dist.run_commands()

  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "build\bdist.win32\egg\setuptools\command\install.py", line 61, in run

  File "C:\Python27\lib\distutils\command\install.py", line 575, in run

    self.run_command(cmd_name)

  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "C:\Python27\lib\distutils\command\install_data.py", line 58, in run

    dir = convert_path(f[0])

  File "C:\Python27\lib\distutils\util.py", line 126, in convert_path

    raise ValueError, "path '%s' cannot end with '/'" % pathname

ValueError: path 'etltest/samples/test/dataMart/' cannot end with '/'

----------------------------------------
Cleaning up...
Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\use
rs\\<user>\\appdata\\local\\temp\\pip_build_<user>\\etlTest\\setup.py';exec(co
mpile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __
file__, 'exec'))" install --record c:\users\<user>\appdata\local\temp\pip-thrq6
0-record\install-record.txt --single-version-externally-managed --compile failed
 with error code 1 in c:\users\<user>\appdata\local\temp\pip_build_<user>\etlT
est
Storing debug log for failure in C:\Users\<user>\pip\pip.log

C:\Windows\system32>pip install etlTest^A
```

**Comment by OpenDataAlex** [comment]
This issue is now resolved.  Removed the offending '/'s from the data files in setup.py
